const STORAGE_KEY='big-gains-v2';
const LEGACY_KEY='big-gains-v1';
const DEFAULT_REST=150;
const WEEK_PLAN={0:'Rest',1:'Push',2:'Pull',3:'Legs',4:'Push',5:'Pull',6:'Legs'};
const DEFAULT_ROUTINES={
  Push:{label:'Jorge Push',exercises:['Seated Machine Chest Press','Incline Iso Machine Press','Iso Machine Shoulder Press','Seated Pec Deck','Triceps Pushdown','Overhead Triceps Extension']},
  Pull:{label:'Pull — Back + Biceps',exercises:['Lat Pulldown','Seated Cable Row','Chest-Supported Row','Reverse Pec Deck','Dumbbell Curl','Hammer Curl']},
  Legs:{label:'Legs + Core',exercises:['Leg Press','Leg Extension','Seated Leg Curl','Romanian Deadlift','Standing Calf Raise','Cable Crunch','Hanging Knee Raise']},
  Cardio:{label:'Cardio',exercises:['Treadmill Run']},
  Other:{label:'Blank workout',exercises:[]}
};
const RAW=[
['Seated Machine Chest Press','Push','Chest','Machine'],['Incline Iso Machine Press','Push','Chest','Machine'],['Smith Machine Incline Press','Push','Chest','Smith Machine'],['Barbell Bench Press','Push','Chest','Barbell'],['Dumbbell Bench Press','Push','Chest','Dumbbell'],['Incline Dumbbell Press','Push','Chest','Dumbbell'],['Cable Chest Fly','Push','Chest','Cable'],['Seated Pec Deck','Push','Chest','Machine'],['Push-Up','Push','Chest','Bodyweight'],['Dips','Push','Chest / Triceps','Bodyweight'],
['Iso Machine Shoulder Press','Push','Shoulders','Machine'],['Dumbbell Shoulder Press','Push','Shoulders','Dumbbell'],['Barbell Overhead Press','Push','Shoulders','Barbell'],['Machine Shoulder Press','Push','Shoulders','Machine'],['Dumbbell Lateral Raise','Push','Shoulders','Dumbbell'],['Cable Lateral Raise','Push','Shoulders','Cable'],['Reverse Pec Deck','Pull','Rear Delts','Machine'],['Face Pull','Pull','Rear Delts','Cable'],
['Overhead Triceps Extension','Push','Triceps','Cable'],['Triceps Pushdown','Push','Triceps','Cable'],['Rope Pushdown','Push','Triceps','Cable'],['Skull Crusher','Push','Triceps','EZ Bar'],['Close-Grip Bench Press','Push','Triceps','Barbell'],['Single-Arm Cable Extension','Push','Triceps','Cable'],
['Lat Pulldown','Pull','Back','Cable'],['Assisted Pull-Up','Pull','Back','Machine'],['Pull-Up','Pull','Back','Bodyweight'],['Seated Cable Row','Pull','Back','Cable'],['Chest-Supported Row','Pull','Back','Machine'],['T-Bar Row','Pull','Back','Machine'],['Barbell Row','Pull','Back','Barbell'],['One-Arm Dumbbell Row','Pull','Back','Dumbbell'],['Iso-Lateral Row','Pull','Back','Machine'],['Straight-Arm Pulldown','Pull','Back','Cable'],['Machine Pullover','Pull','Back','Machine'],['Rack Pull','Pull','Back','Barbell'],
['Dumbbell Curl','Pull','Biceps','Dumbbell'],['Hammer Curl','Pull','Biceps','Dumbbell'],['Incline Dumbbell Curl','Pull','Biceps','Dumbbell'],['Preacher Curl','Pull','Biceps','EZ Bar'],['Machine Preacher Curl','Pull','Biceps','Machine'],['Cable Curl','Pull','Biceps','Cable'],['Bayesian Cable Curl','Pull','Biceps','Cable'],['EZ-Bar Curl','Pull','Biceps','EZ Bar'],
['Back Squat','Legs','Quads / Glutes','Barbell'],['Front Squat','Legs','Quads','Barbell'],['Hack Squat','Legs','Quads / Glutes','Machine'],['Leg Press','Legs','Quads / Glutes','Machine'],['Smith Machine Squat','Legs','Quads / Glutes','Smith Machine'],['Goblet Squat','Legs','Quads / Glutes','Dumbbell'],['Bulgarian Split Squat','Legs','Quads / Glutes','Dumbbell'],['Walking Lunge','Legs','Quads / Glutes','Dumbbell'],['Leg Extension','Legs','Quads','Machine'],
['Romanian Deadlift','Legs','Hamstrings / Glutes','Barbell'],['Dumbbell Romanian Deadlift','Legs','Hamstrings / Glutes','Dumbbell'],['Seated Leg Curl','Legs','Hamstrings','Machine'],['Lying Leg Curl','Legs','Hamstrings','Machine'],['Hip Thrust','Legs','Glutes','Barbell'],['Glute Bridge','Legs','Glutes','Bodyweight'],['Cable Pull-Through','Legs','Glutes','Cable'],['Standing Calf Raise','Legs','Calves','Machine'],['Seated Calf Raise','Legs','Calves','Machine'],
['Cable Crunch','Legs','Core','Cable'],['Hanging Knee Raise','Legs','Core','Bodyweight'],['Hanging Leg Raise','Legs','Core','Bodyweight'],['Ab Wheel Rollout','Legs','Core','Bodyweight'],['Plank','Legs','Core','Bodyweight'],['Side Plank','Legs','Core','Bodyweight'],['Pallof Press','Legs','Core','Cable'],['Machine Crunch','Legs','Core','Machine'],['Russian Twist','Legs','Core','Bodyweight'],['Dead Bug','Legs','Core','Bodyweight'],
['Treadmill Run','Cardio','Cardio','Treadmill'],['Outdoor Run','Cardio','Cardio','None'],['Incline Walk','Cardio','Cardio','Treadmill'],['Stair Climber','Cardio','Cardio','Machine'],['Stationary Bike','Cardio','Cardio','Bike'],['Elliptical','Cardio','Cardio','Machine'],['Rowing Machine','Cardio','Cardio','Machine'],
['Deadlift','Other','Full Body','Barbell'],['Trap Bar Deadlift','Other','Full Body','Trap Bar'],['Farmer Carry','Other','Full Body','Dumbbell'],['Kettlebell Swing','Other','Full Body','Kettlebell']
];
const slug=v=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const EXERCISES=RAW.map(([name,day,muscle,equipment])=>({id:slug(name),name,day,muscle,equipment}));
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
let state=loadState();
let selectedDay=(state.activeWorkout&&state.activeWorkout.type)||todaysWorkout();
let active=state.activeWorkout||null;
let workoutTicker=null,timerTicker=null,timerRemaining=DEFAULT_REST,deferredPrompt=null,cancelArmedUntil=0;
let routineDraftDay=selectedDay,routineDraft=[];
function blankState(){return {version:4,workouts:[],weights:[],prs:{},activeWorkout:null,restTimerEndsAt:null,customRoutines:{}};}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved)return {...blankState(),...saved,customRoutines:saved.customRoutines||{}};const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY));if(legacy){const migrated={...blankState(),weights:legacy.weights||[],workouts:[]};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated;}}catch(e){console.warn('Could not load Big Gains data',e);}return blankState();}
function saveState(){state.activeWorkout=active;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function autosave(){saveState();renderHero();}
function todaysWorkout(){const day=WEEK_PLAN[new Date().getDay()];return day==='Rest'?'Push':day;}
function routineFor(day){const custom=state.customRoutines&&state.customRoutines[day];return Array.isArray(custom)?custom:DEFAULT_ROUTINES[day].exercises.map(name=>slug(name));}
function routineLabel(day){return `${DEFAULT_ROUTINES[day].label}${state.customRoutines&&state.customRoutines[day]?' · Custom':''}`;}
function fmtDate(iso){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(iso));}
function fmtDateLong(iso){return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date(iso));}
function fmtTime(seconds){seconds=Math.max(0,Math.floor(seconds));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function startOfWeek(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-d.getDay());return d;}
function volumeForWorkout(w){return (w.exercises||[]).flatMap(e=>e.sets||[]).filter(s=>s.completed&&!s.warmup).reduce((n,s)=>n+(Number(s.weight)||0)*(Number(s.reps)||0),0);}
function volumeForExercise(e){return (e.sets||[]).filter(s=>!s.warmup).reduce((n,s)=>n+(Number(s.weight)||0)*(Number(s.reps)||0),0);}
function estimate1RM(w,r){return r>0?Math.round(w*(1+r/30)):0;}
function renderGreeting(){const h=new Date().getHours();$('greeting').textContent=`Good ${h<12?'morning':h<18?'afternoon':'evening'}, Jorge.`;$('nextWorkout').textContent=todaysWorkout()==='Legs'?'Legs + Core':todaysWorkout();}
function renderHero(){const button=$('startWorkout'),note=$('heroNote');if(active){button.textContent=`Resume ${active.type==='Legs'?'Legs + Core':active.type}`;note.textContent=`Workout in progress · ${active.exercises.length} exercises saved`;return;}button.textContent='Start planned workout';note.textContent='Your plan is ready. Tap once and train.';}
function renderStats(){$('weeklyWorkouts').textContent=state.workouts.filter(w=>new Date(w.completedAt)>=startOfWeek()).length;$('trainingVolume').textContent=`${Math.round(state.workouts.reduce((n,w)=>n+volumeForWorkout(w),0)).toLocaleString('en-US')} lb`;$('prCount').textContent=Object.keys(state.prs||{}).length;$('latestWeight').textContent=state.weights[0]?`${state.weights[0].weight} lb`:'—';}
function renderSelectors(){document.querySelectorAll('#dayTabs button').forEach(b=>b.classList.toggle('active',b.dataset.day===selectedDay));$('routineSelect').innerHTML=`<option value="${selectedDay}">${escapeHtml(routineLabel(selectedDay))}</option>`;const list=EXERCISES.filter(e=>e.day===selectedDay||selectedDay==='Other');$('quickExerciseSelect').innerHTML=list.map(e=>`<option value="${e.id}">${escapeHtml(e.name)} — ${escapeHtml(e.equipment)}</option>`).join('');}
function renderEquipment(){if($('equipmentFilter').options.length>1)return;[...new Set(EXERCISES.map(e=>e.equipment))].sort().forEach(eq=>$('equipmentFilter').add(new Option(eq,eq)));}
function renderLibrary(){renderSelectors();const q=$('exerciseSearch').value.trim().toLowerCase(),eq=$('equipmentFilter').value;const list=EXERCISES.filter(e=>(e.day===selectedDay||selectedDay==='Other')&&(!q||`${e.name} ${e.muscle} ${e.equipment}`.toLowerCase().includes(q))&&(eq==='all'||e.equipment===eq));$('exerciseLibrary').innerHTML=list.length?list.map(e=>`<article class="exercise-card ${active&&active.exercises.some(x=>x.id===e.id)?'added':''}"><div><span class="exercise-muscle">${escapeHtml(e.muscle)}</span><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(e.equipment)}</p></div><button type="button" class="add-exercise primary compact" data-add="${e.id}">${active&&active.exercises.some(x=>x.id===e.id)?'Added':'Add'}</button></article>`).join(''):'<div class="no-results">No matching exercises.</div>';}
function lastPerformance(name){for(const w of state.workouts){const e=(w.exercises||[]).find(x=>x.name.toLowerCase()===name.toLowerCase());if(e){const sets=e.sets.filter(s=>s.completed&&!s.warmup);if(sets.length)return {date:w.completedAt,sets};}}return null;}
function makeExercise(ex){const last=lastPerformance(ex.name),prior=last?last.sets:[],working=prior[0]?Number(prior[0].weight)||0:0,warm=working?Math.round(working*.6/5)*5:0;return {id:ex.id,name:ex.name,muscle:ex.muscle,equipment:ex.equipment,sets:[{id:uid(),weight:warm,reps:10,warmup:true,completed:false},...Array.from({length:3},(_,i)=>({id:uid(),weight:prior[i]?Number(prior[i].weight)||working:working,reps:prior[i]?Number(prior[i].reps)||'':'',warmup:false,completed:false}))]};}
function showActive(scroll=true){if(!active)return;selectedDay=active.type;$('activePanel').classList.remove('hidden');$('cancelWorkout').classList.remove('hidden');$('cancelWorkout').textContent='Cancel';$('activeWorkoutTitle').textContent=active.type==='Legs'?'Legs + Core':active.type;clearInterval(workoutTicker);workoutTicker=setInterval(renderWorkoutClock,1000);renderWorkoutClock();renderActive();renderLibrary();resumeRestTimer();if(scroll)$('activePanel').scrollIntoView({behavior:'smooth',block:'start'});}
function startWorkout(day=selectedDay,load=true){if(active){showActive(true);return;}selectedDay=day;active={id:uid(),type:day,startedAt:new Date().toISOString(),exercises:[]};if(load)loadRoutine(day,false);autosave();showActive(true);}
function addExercise(id,scroll=true){if(!active)startWorkout(selectedDay,false);if(active.exercises.some(e=>e.id===id))return;const ex=EXERCISES.find(e=>e.id===id);if(!ex)return;active.exercises.push(makeExercise(ex));autosave();renderActive();renderLibrary();if(scroll)$('activePanel').scrollIntoView({behavior:'smooth',block:'start'});}
function loadRoutine(day=selectedDay,scroll=true){if(!active)startWorkout(day,false);routineFor(day).forEach(id=>{const ex=EXERCISES.find(e=>e.id===id);if(ex&&!active.exercises.some(x=>x.id===ex.id))active.exercises.push(makeExercise(ex));});autosave();renderActive();renderLibrary();if(scroll)$('activePanel').scrollIntoView({behavior:'smooth',block:'start'});}
function renderWorkoutClock(){if(active)$('workoutClock').textContent=fmtTime((Date.now()-new Date(active.startedAt))/1000);}
function stepper(field,ei,si,value,step){return `<div class="stepper"><button type="button" data-adjust="-${step}" data-field="${field}" data-ei="${ei}" data-si="${si}">−</button><input data-field="${field}" data-ei="${ei}" data-si="${si}" type="number" min="0" step="${step}" inputmode="decimal" value="${value}" placeholder="${field==='weight'?'lb':'reps'}"><button type="button" data-adjust="${step}" data-field="${field}" data-ei="${ei}" data-si="${si}">+</button></div>`;}
function renderActive(){if(!active)return;const box=$('activeExercises');if(!active.exercises.length){box.innerHTML='<div class="empty">Choose a routine or an exercise above.</div>';$('finishWorkout').disabled=true;return;}box.innerHTML=active.exercises.map((e,ei)=>{const last=lastPerformance(e.name),previous=last?`Last: ${last.sets.map(s=>`${s.weight} × ${s.reps}`).join(' · ')}`:'First time logged.';const sets=e.sets.map((s,si)=>`<div class="set-line ${s.completed?'completed':''}"><span class="set-number">${s.warmup?'W':si}</span>${stepper('weight',ei,si,s.weight,5)}${stepper('reps',ei,si,s.reps,1)}<button type="button" class="set-done" data-complete-set="1" data-ei="${ei}" data-si="${si}">✓</button></div>`).join('');return `<article class="active-exercise"><div class="exercise-head"><div><span class="exercise-muscle">${escapeHtml(e.muscle)}</span><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(e.equipment)}</p></div><button type="button" class="remove-exercise" data-remove-exercise="${ei}">✕</button></div><div class="previous-note">${escapeHtml(previous)}</div><div class="set-grid">${sets}</div><button type="button" class="add-set" data-add-set="${ei}">+ Add set</button></article>`;}).join('');$('finishWorkout').disabled=!active.exercises.some(e=>e.sets.some(s=>s.completed));}
function startRestTimer(){state.restTimerEndsAt=Date.now()+DEFAULT_REST*1000;saveState();runRestTimer();}
function resumeRestTimer(){if(!state.restTimerEndsAt)return;if(state.restTimerEndsAt<=Date.now()){state.restTimerEndsAt=null;saveState();return;}runRestTimer();}
function runRestTimer(){clearInterval(timerTicker);$('timerCard').classList.remove('hidden');$('timerNext').textContent='Recover. Your next set is waiting.';const tick=()=>{timerRemaining=Math.max(0,Math.ceil((state.restTimerEndsAt-Date.now())/1000));renderTimer();if(timerRemaining<=0){clearInterval(timerTicker);state.restTimerEndsAt=null;saveState();$('timerNext').textContent='Rest complete. Go earn the next one.';if(navigator.vibrate)navigator.vibrate([150,80,150]);}};tick();timerTicker=setInterval(tick,1000);}
function renderTimer(){$('timerDisplay').textContent=fmtTime(timerRemaining);}
function discardWorkout(){active=null;state.activeWorkout=null;state.restTimerEndsAt=null;saveState();clearInterval(workoutTicker);clearInterval(timerTicker);$('activePanel').classList.add('hidden');$('timerCard').classList.add('hidden');$('cancelWorkout').classList.add('hidden');$('cancelWorkout').textContent='Cancel';cancelArmedUntil=0;renderHero();renderLibrary();$('workoutPanel').scrollIntoView({behavior:'smooth'});}
function finishWorkout(){if(!active)return;const completed=active.exercises.map(e=>({...e,sets:e.sets.filter(s=>s.completed)})).filter(e=>e.sets.length);if(!completed.length)return;const completedAt=new Date().toISOString(),durationSeconds=Math.floor((Date.now()-new Date(active.startedAt))/1000),workout={...active,completedAt,durationSeconds,exercises:completed};let newPRs=0;completed.forEach(e=>e.sets.filter(s=>!s.warmup).forEach(s=>{const score=estimate1RM(Number(s.weight),Number(s.reps));if(score>((state.prs[e.id]&&state.prs[e.id].estimated1RM)||0)){state.prs[e.id]={exercise:e.name,estimated1RM:score,weight:Number(s.weight),reps:Number(s.reps),date:completedAt};newPRs++;}}));workout.prs=newPRs;state.workouts.unshift(workout);active=null;state.activeWorkout=null;state.restTimerEndsAt=null;saveState();clearInterval(workoutTicker);clearInterval(timerTicker);$('activePanel').classList.add('hidden');$('timerCard').classList.add('hidden');$('cancelWorkout').classList.add('hidden');$('heroNote').textContent=`Workout saved${newPRs?` · ${newPRs} new PR${newPRs===1?'':'s'}`:''}.`;renderAll();$('top').scrollIntoView({behavior:'smooth'});}
function renderHistory(){const box=$('history');if(!state.workouts.length){box.className='history-list empty';box.textContent='Your completed workouts will appear here.';return;}box.className='history-list';box.innerHTML=state.workouts.slice(0,20).map(w=>`<button type="button" class="history-item" data-history-id="${w.id}"><div><strong>${escapeHtml(w.type==='Legs'?'Legs + Core':w.type)}</strong><small>${fmtDate(w.completedAt)} · ${(w.exercises||[]).flatMap(e=>e.sets||[]).length} sets · ${fmtTime(w.durationSeconds||0)}</small><div class="history-open">View full workout →</div></div><div class="history-meta"><strong>${Math.round(volumeForWorkout(w)).toLocaleString('en-US')} lb</strong><small>${(w.exercises||[]).length} exercises${w.prs?` · ${w.prs} PR${w.prs===1?'':'s'}`:''}</small></div></button>`).join('');}
function openHistory(id){const w=state.workouts.find(x=>x.id===id);if(!w)return;const title=w.type==='Legs'?'Legs + Core':w.type;$('historyDialogTitle').textContent=title;$('historyDialogDate').textContent=fmtDateLong(w.completedAt);const totalSets=(w.exercises||[]).flatMap(e=>e.sets||[]).length;const exercises=(w.exercises||[]).map(e=>{const best=(e.sets||[]).filter(s=>!s.warmup).reduce((winner,s)=>estimate1RM(Number(s.weight),Number(s.reps))>estimate1RM(Number(winner?.weight||0),Number(winner?.reps||0))?s:winner,null);const sets=(e.sets||[]).map((s,i)=>`<div class="history-set"><span class="${s.warmup?'warmup-chip':''}">${s.warmup?'Warm-up':`Set ${i+1}`}</span><strong>${Number(s.weight)||0} lb × ${Number(s.reps)||0}</strong>${best===s&&!s.warmup?'<span class="pr-chip">BEST</span>':'<span></span>'}</div>`).join('');return `<article class="history-exercise"><div class="history-exercise-head"><div><span class="exercise-muscle">${escapeHtml(e.muscle||'Exercise')}</span><h3>${escapeHtml(e.name)}</h3><small>${escapeHtml(e.equipment||'')} · ${Math.round(volumeForExercise(e)).toLocaleString('en-US')} lb volume</small></div></div><div class="history-sets">${sets}</div></article>`;}).join('');$('historyDialogContent').innerHTML=`<div class="history-summary-grid"><div><span>Duration</span><strong>${fmtTime(w.durationSeconds||0)}</strong></div><div><span>Total volume</span><strong>${Math.round(volumeForWorkout(w)).toLocaleString('en-US')} lb</strong></div><div><span>Work completed</span><strong>${(w.exercises||[]).length} exercises · ${totalSets} sets</strong></div></div>${w.prs?`<div class="previous-note">${w.prs} personal record${w.prs===1?'':'s'} earned in this workout.</div>`:''}<div class="history-detail-list">${exercises}</div>`;const dialog=$('historyDialog');if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');}
function closeHistory(){const dialog=$('historyDialog');if(dialog.close)dialog.close();else dialog.removeAttribute('open');}
function openRoutineEditor(){routineDraftDay=selectedDay;routineDraft=[...routineFor(routineDraftDay)];$('routineEditorTitle').textContent=`Edit ${routineDraftDay==='Legs'?'Legs + Core':routineDraftDay}`;renderRoutineEditor();const d=$('routineDialog');if(d.showModal)d.showModal();else d.setAttribute('open','');}
function renderRoutineEditor(){const list=$('routineEditorList');list.innerHTML=routineDraft.length?routineDraft.map((id,i)=>{const e=EXERCISES.find(x=>x.id===id);if(!e)return '';return `<div class="routine-row"><div><span>${i+1}</span><strong>${escapeHtml(e.name)}</strong><small>${escapeHtml(e.muscle)} · ${escapeHtml(e.equipment)}</small></div><div class="routine-row-actions"><button type="button" data-routine-move="up" data-index="${i}" ${i===0?'disabled':''}>↑</button><button type="button" data-routine-move="down" data-index="${i}" ${i===routineDraft.length-1?'disabled':''}>↓</button><button type="button" data-routine-remove="${i}" aria-label="Remove ${escapeHtml(e.name)}">✕</button></div></div>`;}).join(''):'<div class="empty">This routine is empty. Add an exercise below.</div>';const available=EXERCISES.filter(e=>!routineDraft.includes(e.id)).sort((a,b)=>(a.day===routineDraftDay?-1:0)-(b.day===routineDraftDay?-1:0)||a.name.localeCompare(b.name));$('routineExerciseSelect').innerHTML=available.map(e=>`<option value="${e.id}">${escapeHtml(e.name)} — ${escapeHtml(e.equipment)}</option>`).join('');$('addRoutineExercise').disabled=!available.length;}
function closeRoutineEditor(){const d=$('routineDialog');if(d.close)d.close();else d.removeAttribute('open');}
function saveRoutine(){state.customRoutines[routineDraftDay]=[...routineDraft];saveState();renderLibrary();closeRoutineEditor();}
function resetRoutine(){delete state.customRoutines[routineDraftDay];routineDraft=[...routineFor(routineDraftDay)];saveState();renderRoutineEditor();renderLibrary();}
function renderWeights(){const box=$('weightHistory');if(!state.weights.length){box.className='mini-list empty';box.textContent='No weigh-ins yet.';return;}box.className='mini-list';box.innerHTML=state.weights.slice(0,5).map(x=>`<div class="weight-row"><strong>${x.weight} lb</strong><small>${fmtDate(x.date)}</small></div>`).join('');}
function renderAll(){renderGreeting();renderHero();renderStats();renderEquipment();renderLibrary();renderHistory();renderWeights();if(active)showActive(false);}
function bind(id,event,handler){const el=$(id);if(el)el.addEventListener(event,handler);}
bind('dayTabs','click',e=>{const b=e.target.closest('[data-day]');if(!b)return;selectedDay=b.dataset.day;$('equipmentFilter').value='all';$('exerciseSearch').value='';renderLibrary();});
bind('startWorkout','click',()=>active?showActive(true):startWorkout(todaysWorkout(),true));
bind('loadRoutine','click',()=>{if(active)discardWorkout();startWorkout(selectedDay,true);});
bind('editRoutine','click',openRoutineEditor);
bind('addSelectedExercise','click',()=>addExercise($('quickExerciseSelect').value));
bind('exerciseSearch','input',renderLibrary);bind('equipmentFilter','change',renderLibrary);bind('exerciseLibrary','click',e=>{const b=e.target.closest('[data-add]');if(b)addExercise(b.dataset.add);});
bind('cancelWorkout','click',()=>{const now=Date.now();if(now<cancelArmedUntil){discardWorkout();return;}cancelArmedUntil=now+2500;$('cancelWorkout').textContent='Tap again to discard';setTimeout(()=>{if(active&&Date.now()>=cancelArmedUntil)$('cancelWorkout').textContent='Cancel';},2600);});
bind('activeExercises','input',e=>{const {ei,si,field}=e.target.dataset;if(field&&active&&e.target.tagName==='INPUT'){active.exercises[Number(ei)].sets[Number(si)][field]=e.target.value===''?'':Number(e.target.value);autosave();}});
bind('activeExercises','click',e=>{const t=e.target.closest('button');if(!t||!active)return;if(t.dataset.removeExercise!==undefined){active.exercises.splice(Number(t.dataset.removeExercise),1);autosave();renderActive();renderLibrary();return;}if(t.dataset.addSet!==undefined){active.exercises[Number(t.dataset.addSet)].sets.push({id:uid(),weight:'',reps:'',warmup:false,completed:false});autosave();renderActive();return;}if(t.dataset.adjust!==undefined){const set=active.exercises[Number(t.dataset.ei)].sets[Number(t.dataset.si)],field=t.dataset.field;set[field]=Math.max(0,(Number(set[field])||0)+Number(t.dataset.adjust));autosave();renderActive();return;}if(t.dataset.completeSet){const set=active.exercises[Number(t.dataset.ei)].sets[Number(t.dataset.si)];if(!Number(set.weight)||!Number(set.reps))return;set.completed=!set.completed;autosave();renderActive();if(set.completed)startRestTimer();}});
bind('finishWorkout','click',finishWorkout);
bind('timerMinus','click',()=>{if(!state.restTimerEndsAt)return;state.restTimerEndsAt=Math.max(Date.now(),state.restTimerEndsAt-15000);saveState();runRestTimer();});
bind('timerPlus','click',()=>{state.restTimerEndsAt=(state.restTimerEndsAt||Date.now())+15000;saveState();runRestTimer();});
bind('timerSkip','click',()=>{clearInterval(timerTicker);state.restTimerEndsAt=null;saveState();$('timerCard').classList.add('hidden');});
bind('history','click',e=>{const b=e.target.closest('[data-history-id]');if(b)openHistory(b.dataset.historyId);});
bind('closeHistoryDialog','click',closeHistory);bind('historyDialog','click',e=>{if(e.target===$('historyDialog'))closeHistory();});
bind('routineEditorList','click',e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.index);if(b.dataset.routineMove==='up'&&i>0)[routineDraft[i-1],routineDraft[i]]=[routineDraft[i],routineDraft[i-1]];else if(b.dataset.routineMove==='down'&&i<routineDraft.length-1)[routineDraft[i+1],routineDraft[i]]=[routineDraft[i],routineDraft[i+1]];else if(b.dataset.routineRemove!==undefined)routineDraft.splice(Number(b.dataset.routineRemove),1);renderRoutineEditor();});
bind('addRoutineExercise','click',()=>{const id=$('routineExerciseSelect').value;if(id&&!routineDraft.includes(id)){routineDraft.push(id);renderRoutineEditor();}});
bind('saveRoutine','click',saveRoutine);bind('resetRoutine','click',resetRoutine);bind('closeRoutineDialog','click',closeRoutineEditor);bind('routineDialog','click',e=>{if(e.target===$('routineDialog'))closeRoutineEditor();});
bind('weightForm','submit',e=>{e.preventDefault();state.weights.unshift({weight:Number($('bodyweight').value),date:new Date().toISOString()});$('bodyweight').value='';saveState();renderAll();});
bind('exportData','click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`big-gains-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);});
bind('importData','change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported.workouts)||!Array.isArray(imported.weights))throw new Error('Invalid backup');state={...blankState(),...imported,customRoutines:imported.customRoutines||{}};active=state.activeWorkout||null;selectedDay=(active&&active.type)||todaysWorkout();saveState();renderAll();alert('Backup restored.');}catch{alert('That file is not a valid Big Gains backup.');}e.target.value='';});
document.addEventListener('click',e=>{const b=e.target.closest('.bottom-nav button');if(!b)return;const target=$(b.dataset.target);if(!target)return;document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b));target.scrollIntoView({behavior:'smooth',block:'start'});});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').classList.remove('hidden');});
bind('installButton','click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installButton').classList.add('hidden');});
window.addEventListener('pagehide',saveState);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveState();});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn));
renderAll();