const STORAGE_KEY='big-gains-v2';
const LEGACY_KEY='big-gains-v1';
const DEFAULT_REST=150;
const WEEK_PLAN={0:'Rest',1:'Push',2:'Pull',3:'Legs',4:'Push',5:'Pull',6:'Legs'};
const ROUTINES={
  Push:{label:'Jorge Push',exercises:['Seated Machine Chest Press','Incline Iso Machine Press','Iso Machine Shoulder Press','Seated Pec Deck','Triceps Pushdown','Overhead Triceps Extension']},
  Pull:{label:'Pull — Back + Biceps',exercises:['Lat Pulldown','Seated Cable Row','Chest-Supported Row','Reverse Pec Deck','Dumbbell Curl','Hammer Curl']},
  Legs:{label:'Legs + Core',exercises:['Leg Press','Leg Extension','Seated Leg Curl','Romanian Deadlift','Standing Calf Raise','Cable Crunch','Hanging Knee Raise']},
  Cardio:{label:'Cardio',exercises:['Treadmill Run']},
  Other:{label:'Blank workout',exercises:[]}
};
const RAW=[
['Seated Machine Chest Press','Push','Chest','Machine'],['Incline Iso Machine Press','Push','Chest','Machine'],['Smith Machine Incline Press','Push','Chest','Smith Machine'],['Barbell Bench Press','Push','Chest','Barbell'],['Dumbbell Bench Press','Push','Chest','Dumbbell'],['Incline Dumbbell Press','Push','Chest','Dumbbell'],['Cable Chest Fly','Push','Chest','Cable'],['Seated Pec Deck','Push','Chest','Machine'],['Push-Up','Push','Chest','Bodyweight'],['Dips','Push','Chest / Triceps','Bodyweight'],
['Iso Machine Shoulder Press','Push','Shoulders','Machine'],['Dumbbell Shoulder Press','Push','Shoulders','Dumbbell'],['Barbell Overhead Press','Push','Shoulders','Barbell'],['Machine Shoulder Press','Push','Shoulders','Machine'],['Dumbbell Lateral Raise','Push','Shoulders','Dumbbell'],['Cable Lateral Raise','Push','Shoulders','Cable'],['Reverse Pec Deck','Pull','Rear Delts','Machine'],['Face Pull','Pull','Rear Delts','Cable'],
['Overhead Triceps Extension','Push','Triceps','Cable'],['Triceps Pushdown','Push','Triceps','Cable'],['Rope Pushdown','Push','Triceps','Cable'],['Skull Crusher','Push','Triceps','EZ Bar'],['Close-Grip Bench Press','Push','Triceps','Barbell'],['Single-Arm Cable Extension','Push','Triceps','Cable'],
['Lat Pulldown','Pull','Back','Cable'],['Assisted Pull-Up','Pull','Back','Machine'],['Pull-Up','Pull','Back','Bodyweight'],['Seated Cable Row','Pull','Back','Cable'],['Chest-Supported Row','Pull','Back','Machine'],['T-Bar Row','Pull','Back','Machine'],['Barbell Row','Pull','Back','Barbell'],['One-Arm Dumbbell Row','Pull','Back','Dumbbell'],['Iso-Lateral Row','Pull','Back','Machine'],['Straight-Arm Pulldown','Pull','Back','Cable'],['Machine Pullover','Pull','Back','Machine'],['Rack Pull','Pull','Back','Barbell'],
['Dumbbell Curl','Pull','Biceps','Dumbbell'],['Hammer Curl','Pull','Biceps','Dumbbell'],['Incline Dumbbell Curl','Pull','Biceps','Dumbbell'],['Preacher Curl','Pull','Biceps','EZ Bar'],['Machine Preacher Curl','Pull','Biceps','Machine'],['Cable Curl','Pull','Biceps','Cable'],['Bayesian Cable Curl','Pull','Biceps','Cable'],['EZ-Bar Curl','Pull','Biceps','EZ Bar'],
['Back Squat','Legs','Quads / Glutes','Barbell'],['Front Squat','Legs','Quads','Barbell'],['Hack Squat','Legs','Quads / Glutes','Machine'],['Leg Press','Legs','Quads / Glutes','Machine'],['Smith Machine Squat','Legs','Quads / Glutes','Smith Machine'],['Goblet Squat','Legs','Quads / Glutes','Dumbbell'],['Bulgarian Split Squat','Legs','Quads / Glutes','Dumbbell'],['Walking Lunge','Legs','Quads / Glutes','Dumbbell'],['Leg Extension','Legs','Quads','Machine'],
['Romanian Deadlift','Legs','Hamstrings / Glutes','Barbell'],['Dumbbell Romanian Deadlift','Legs','Hamstrings / Glutes','Dumbbell'],['Seated Leg Curl','Legs','Hamstrings','Machine'],['Lying Leg Curl','Legs','Hamstrings','Machine'],['Hip Thrust','Legs','Glutes','Barbell'],['Glute Bridge','Legs','Glutes','Bodyweight'],['Cable Pull-Through','Legs','Glutes','Cable'],['Standing Calf Raise','Legs','Calves','Machine'],['Seated Calf Raise','Legs','Calves','Machine'],
['Cable Crunch','Legs','Core','Cable'],['Hanging Knee Raise','Legs','Core','Bodyweight'],['Hanging Leg Raise','Legs','Core','Bodyweight'],['Ab Wheel Rollout','Legs','Core','Bodyweight'],['Plank','Legs','Core','Bodyweight'],['Side Plank','Legs','Core','Bodyweight'],['Pallof Press','Legs','Core','Cable'],['Machine Crunch','Legs','Core','Machine'],['Russian Twist','Legs','Core','Bodyweight'],['Dead Bug','Legs','Core','Bodyweight'],
['Treadmill Run','Cardio','Cardio','Treadmill'],['Outdoor Run','Cardio','Cardio','None'],['Incline Walk','Cardio','Cardio','Treadmill'],['Stair Climber','Cardio','Cardio','Machine'],['Stationary Bike','Cardio','Cardio','Bike'],['Elliptical','Cardio','Cardio','Machine'],['Rowing Machine','Cardio','Cardio','Machine'],
['Deadlift','Other','Full Body','Barbell'],['Trap Bar Deadlift','Other','Full Body','Trap Bar'],['Farmer Carry','Other','Full Body','Dumbbell'],['Kettlebell Swing','Other','Full Body','Kettlebell']
];
const slug=v=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const EXERCISES=RAW.map(([name,day,muscle,equipment])=>({id:slug(name),name,day,muscle,equipment}));
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
let state=loadState(),selectedDay=todaysWorkout(),active=null,workoutTicker=null,timerTicker=null,timerRemaining=DEFAULT_REST,deferredPrompt=null;
function blankState(){return {version:2,workouts:[],weights:[],prs:{}}}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved)return {...blankState(),...saved};const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY));if(legacy){const migrated={...blankState(),weights:legacy.weights||[],workouts:[]};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}}catch{}return blankState()}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function todaysWorkout(){const d=WEEK_PLAN[new Date().getDay()];return d==='Rest'?'Push':d}
function fmtDate(iso){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(iso))}
function fmtTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function startOfWeek(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-d.getDay());return d}
function volumeForWorkout(w){return (w.exercises||[]).flatMap(e=>e.sets||[]).filter(s=>s.completed&&!s.warmup).reduce((n,s)=>n+(+s.weight||0)*(+s.reps||0),0)}
function estimate1RM(w,r){return r>0?Math.round(w*(1+r/30)):0}
function renderGreeting(){const h=new Date().getHours();$('greeting').textContent=`Good ${h<12?'morning':h<18?'afternoon':'evening'}, Jorge.`;$('nextWorkout').textContent=todaysWorkout()==='Legs'?'Legs + Core':todaysWorkout()}
function renderStats(){$('weeklyWorkouts').textContent=state.workouts.filter(w=>new Date(w.completedAt)>=startOfWeek()).length;$('trainingVolume').textContent=`${Math.round(state.workouts.reduce((n,w)=>n+volumeForWorkout(w),0)).toLocaleString('en-US')} lb`;$('prCount').textContent=Object.keys(state.prs||{}).length;$('latestWeight').textContent=state.weights[0]?`${state.weights[0].weight} lb`:'—'}
function renderSelectors(){document.querySelectorAll('#dayTabs button').forEach(b=>b.classList.toggle('active',b.dataset.day===selectedDay));$('routineSelect').innerHTML=`<option value="${selectedDay}">${ROUTINES[selectedDay].label}</option>`;const list=EXERCISES.filter(e=>e.day===selectedDay||selectedDay==='Other');$('quickExerciseSelect').innerHTML=list.map(e=>`<option value="${e.id}">${escapeHtml(e.name)} — ${escapeHtml(e.equipment)}</option>`).join('')}
function renderEquipment(){if($('equipmentFilter').options.length>1)return;[...new Set(EXERCISES.map(e=>e.equipment))].sort().forEach(eq=>$('equipmentFilter').add(new Option(eq,eq)))}
function renderLibrary(){renderSelectors();const q=$('exerciseSearch').value.trim().toLowerCase(),eq=$('equipmentFilter').value;const list=EXERCISES.filter(e=>(e.day===selectedDay||selectedDay==='Other')&&(!q||`${e.name} ${e.muscle} ${e.equipment}`.toLowerCase().includes(q))&&(eq==='all'||e.equipment===eq));$('exerciseLibrary').innerHTML=list.map(e=>`<article class="exercise-card ${active?.exercises.some(x=>x.id===e.id)?'added':''}"><div><span class="exercise-muscle">${escapeHtml(e.muscle)}</span><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(e.equipment)}</p></div><button class="add-exercise primary compact" data-add="${e.id}">${active?.exercises.some(x=>x.id===e.id)?'Added':'Add'}</button></article>`).join('')}
function lastPerformance(name){for(const w of state.workouts){const e=(w.exercises||[]).find(x=>x.name.toLowerCase()===name.toLowerCase());if(e){const sets=e.sets.filter(s=>s.completed&&!s.warmup);if(sets.length)return {date:w.completedAt,sets}}}return null}
function makeExercise(ex){const last=lastPerformance(ex.name),prior=last?.sets||[],working=prior[0]?.weight||0,warm=working?Math.round(working*.6/5)*5:0;return {id:ex.id,name:ex.name,muscle:ex.muscle,equipment:ex.equipment,sets:[{id:uid(),weight:warm,reps:10,warmup:true,completed:false},...Array.from({length:3},(_,i)=>({id:uid(),weight:prior[i]?.weight||working,reps:prior[i]?.reps||'',warmup:false,completed:false}))]}}
function startWorkout(day=selectedDay,load=true){selectedDay=day;active={id:uid(),type:day,startedAt:new Date().toISOString(),exercises:[]};if(load)loadRoutine(day,false);$('activePanel').classList.remove('hidden');$('cancelWorkout').classList.remove('hidden');$('activeWorkoutTitle').textContent=day==='Legs'?'Legs + Core':day;clearInterval(workoutTicker);workoutTicker=setInterval(renderWorkoutClock,1000);renderWorkoutClock();renderActive();renderLibrary();$('activePanel').scrollIntoView({behavior:'smooth'})}
function addExercise(id,scroll=true){if(!active)startWorkout(selectedDay,false);if(active.exercises.some(e=>e.id===id))return;const ex=EXERCISES.find(e=>e.id===id);if(!ex)return;active.exercises.push(makeExercise(ex));renderActive();renderLibrary();if(scroll)$('activePanel').scrollIntoView({behavior:'smooth',block:'start'})}
function loadRoutine(day=selectedDay,scroll=true){if(!active)startWorkout(day,false);ROUTINES[day].exercises.forEach(name=>{const ex=EXERCISES.find(e=>e.name===name);if(ex&&!active.exercises.some(x=>x.id===ex.id))active.exercises.push(makeExercise(ex))});renderActive();renderLibrary();if(scroll)$('activePanel').scrollIntoView({behavior:'smooth'})}
function renderWorkoutClock(){if(active)$('workoutClock').textContent=fmtTime(Math.max(0,Math.floor((Date.now()-new Date(active.startedAt))/1000)))}
function renderActive(){if(!active)return;const box=$('activeExercises');if(!active.exercises.length){box.innerHTML='<div class="empty">Choose a routine or an exercise from the dropdown above.</div>';$('finishWorkout').disabled=true;return}box.innerHTML=active.exercises.map((e,ei)=>{const last=lastPerformance(e.name),previous=last?`Last: ${last.sets.map(s=>`${s.weight} × ${s.reps}`).join(' · ')}`:'First time logged.';return `<article class="active-exercise"><div class="exercise-head"><div><span class="exercise-muscle">${escapeHtml(e.muscle)}</span><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(e.equipment)}</p></div><button class="remove-exercise" data-remove-exercise="${ei}">✕</button></div><div class="previous-note">${escapeHtml(previous)}</div><div class="set-grid">${e.sets.map((s,si)=>`<div class="set-line ${s.completed?'completed':''}"><span class="set-number">${s.warmup?'W':si}</span><input data-field="weight" data-ei="${ei}" data-si="${si}" type="number" min="0" step="0.5" inputmode="decimal" value="${s.weight}" placeholder="lb"><input data-field="reps" data-ei="${ei}" data-si="${si}" type="number" min="1" step="1" inputmode="numeric" value="${s.reps}" placeholder="reps"><button class="set-done" data-complete-set="1" data-ei="${ei}" data-si="${si}">✓</button></div>`).join('')}</div><button class="add-set" data-add-set="${ei}">+ Add set</button></article>`}).join('');$('finishWorkout').disabled=!active.exercises.some(e=>e.sets.some(s=>s.completed))}
function startRestTimer(){timerRemaining=DEFAULT_REST;$('timerCard').classList.remove('hidden');renderTimer();clearInterval(timerTicker);timerTicker=setInterval(()=>{timerRemaining--;renderTimer();if(timerRemaining<=0){clearInterval(timerTicker);$('timerNext').textContent='Rest complete. Go earn the next one.';navigator.vibrate?.([150,80,150])}},1000)}
function renderTimer(){$('timerDisplay').textContent=fmtTime(Math.max(0,timerRemaining))}
function finishWorkout(){if(!active)return;const completed=active.exercises.map(e=>({...e,sets:e.sets.filter(s=>s.completed)})).filter(e=>e.sets.length);if(!completed.length)return;const completedAt=new Date().toISOString(),durationSeconds=Math.floor((Date.now()-new Date(active.startedAt))/1000),workout={...active,completedAt,durationSeconds,exercises:completed};let newPRs=0;completed.forEach(e=>e.sets.filter(s=>!s.warmup).forEach(s=>{const score=estimate1RM(+s.weight,+s.reps);if(score>(state.prs[e.id]?.estimated1RM||0)){state.prs[e.id]={exercise:e.name,estimated1RM:score,weight:+s.weight,reps:+s.reps,date:completedAt};newPRs++}}));workout.prs=newPRs;state.workouts.unshift(workout);saveState();active=null;clearInterval(workoutTicker);clearInterval(timerTicker);$('activePanel').classList.add('hidden');$('timerCard').classList.add('hidden');$('cancelWorkout').classList.add('hidden');$('heroNote').textContent=`Workout saved${newPRs?` · ${newPRs} new PR${newPRs===1?'':'s'}`:''}.`;renderAll();$('top').scrollIntoView({behavior:'smooth'})}
function renderHistory(){const box=$('history');if(!state.workouts.length){box.className='history-list empty';box.textContent='Your completed workouts will appear here.';return}box.className='history-list';box.innerHTML=state.workouts.slice(0,10).map(w=>`<div class="history-item"><div><strong>${escapeHtml(w.type==='Legs'?'Legs + Core':w.type)}</strong><small>${fmtDate(w.completedAt)} · ${(w.exercises||[]).flatMap(e=>e.sets||[]).length} sets · ${fmtTime(w.durationSeconds||0)}</small></div><div class="history-meta"><strong>${Math.round(volumeForWorkout(w)).toLocaleString('en-US')} lb</strong><small>${(w.exercises||[]).length} exercises</small></div></div>`).join('')}
function renderWeights(){const box=$('weightHistory');if(!state.weights.length){box.className='mini-list empty';box.textContent='No weigh-ins yet.';return}box.className='mini-list';box.innerHTML=state.weights.slice(0,5).map(w=>`<div class="weight-row"><strong>${w.weight} lb</strong><small>${fmtDate(w.date)}</small></div>`).join('')}
function renderAll(){renderGreeting();renderStats();renderEquipment();renderLibrary();renderHistory();renderWeights();if(active)renderActive()}
$('dayTabs').addEventListener('click',e=>{const day=e.target.dataset.day;if(!day)return;selectedDay=day;$('equipmentFilter').value='all';$('exerciseSearch').value='';renderLibrary()});
$('startWorkout').addEventListener('click',()=>startWorkout(todaysWorkout(),true));
$('loadRoutine').addEventListener('click',()=>{if(active&&active.type!==selectedDay){if(!confirm('Replace the current workout?'))return;active=null}startWorkout(selectedDay,true)});
$('addSelectedExercise').addEventListener('click',()=>addExercise($('quickExerciseSelect').value));
$('exerciseSearch').addEventListener('input',renderLibrary);$('equipmentFilter').addEventListener('change',renderLibrary);$('exerciseLibrary').addEventListener('click',e=>{if(e.target.dataset.add)addExercise(e.target.dataset.add)});
$('cancelWorkout').addEventListener('click',()=>{if(!active||confirm('Discard this workout?')){active=null;clearInterval(workoutTicker);clearInterval(timerTicker);$('activePanel').classList.add('hidden');$('timerCard').classList.add('hidden');$('cancelWorkout').classList.add('hidden');renderLibrary()}});
$('activeExercises').addEventListener('input',e=>{const {ei,si,field}=e.target.dataset;if(field&&active)active.exercises[+ei].sets[+si][field]=e.target.value===''?'':+e.target.value});
$('activeExercises').addEventListener('click',e=>{if(e.target.dataset.removeExercise!==undefined){active.exercises.splice(+e.target.dataset.removeExercise,1);renderActive();renderLibrary();return}if(e.target.dataset.addSet!==undefined){active.exercises[+e.target.dataset.addSet].sets.push({id:uid(),weight:'',reps:'',warmup:false,completed:false});renderActive();return}if(e.target.dataset.completeSet){const set=active.exercises[+e.target.dataset.ei].sets[+e.target.dataset.si];if(!set.weight||!set.reps)return;set.completed=!set.completed;renderActive();if(set.completed)startRestTimer()}});
$('finishWorkout').addEventListener('click',finishWorkout);$('timerMinus').addEventListener('click',()=>{timerRemaining=Math.max(0,timerRemaining-15);renderTimer()});$('timerPlus').addEventListener('click',()=>{timerRemaining+=15;renderTimer()});$('timerSkip').addEventListener('click',()=>{clearInterval(timerTicker);$('timerCard').classList.add('hidden')});
$('weightForm').addEventListener('submit',e=>{e.preventDefault();state.weights.unshift({weight:+$('bodyweight').value,date:new Date().toISOString()});$('bodyweight').value='';saveState();renderAll()});
$('exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`big-gains-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)});
$('importData').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported.workouts)||!Array.isArray(imported.weights))throw 0;if(confirm('Replace the data on this device with this backup?')){state={...blankState(),...imported};saveState();renderAll()}}catch{alert('That file is not a valid Big Gains backup.')}e.target.value=''});
document.querySelectorAll('.bottom-nav button').forEach(btn=>btn.addEventListener('click',()=>{$(btn.dataset.target).scrollIntoView({behavior:'smooth'})}));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').classList.remove('hidden')});$('installButton').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installButton').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
renderAll();